# Generated by Django 3.2.8 on 2021-11-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_remove_profile_neighbourhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='watch.profile'),
        ),
    ]
