# Generated by Django 3.2.8 on 2021-11-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_auto_20211103_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
    ]
